# Generated by Django 5.2 on 2025-10-04

from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        help_text="Human-readable name of the project.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=80,
                        blank=True,
                        help_text="URL-safe identifier (auto-generated from name if left blank). Unique per owner.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description (do not store PII).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=16,
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Lifecycle status of the project.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Lightweight structured annotations (no PII, keys/values kept minimal).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        help_text="User who owns and manages this project.",
                    ),
                ),
            ],
            options={
                "db_table": "api_project",
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=("owner", "slug"),
                name="project_owner_slug_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=("owner", "status"),
                name="project_owner_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"),
                name="project_unique_owner_slug",
                condition=Q(slug__isnull=False) & ~Q(slug=""),
            ),
        ),
    ]
