# Generated by Django 5.2.5 on 2025-10-05 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterConstraint(
            model_name="project",
            name="project_unique_owner_slug",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False), models.Q(("slug", ""), _negated=True)),
                fields=("owner", "slug"),
                name="project_unique_owner_slug",
                violation_error_message="Slug must be unique for the same owner.",
            ),
        ),
    ]
