# Generated by Django 5.2.5 on 2025-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_agentprofile_scopes_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
