# Generated by Django 5.2.2 on 2025-07-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JaredLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_cible",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'agent IA concerné (le cas échéant)",
                        max_length=100,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message ou instruction envoyé à Jared ou à un autre agent"
                    ),
                ),
                (
                    "reponse",
                    models.TextField(
                        blank=True,
                        help_text="Réponse générée ou apportée à l'utilisateur",
                        null=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("todo", "À faire"),
                            ("done", "Terminé"),
                            ("waiting", "En attente"),
                            ("alert", "Alerte"),
                            ("note", "Note privée"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Élevée"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Mots-clés ou catégories (séparés par virgules)",
                        max_length=255,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Échéance éventuelle pour la tâche ou l'action",
                        null=True,
                    ),
                ),
                (
                    "suivi",
                    models.BooleanField(
                        default=True, help_text="Cette entrée est-elle suivie par Jared ?"
                    ),
                ),
                (
                    "confidentiel",
                    models.BooleanField(
                        default=False, help_text="Visible uniquement par l'utilisateur ?"
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée du Journal de Jared",
                "verbose_name_plural": "Journal Stratégique de Jared",
                "ordering": ["-horodatage"],
            },
        ),
    ]
