# Generated by Django 5.2.2 on 2025-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("assistant_id", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                ("model", models.CharField(default="gpt-4o", max_length=50)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Champs supplémentaires : dépendances, émotions, contraintes…",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profil d'Agent IA",
                "verbose_name_plural": "Profils des Agents IA",
            },
        ),
        migrations.CreateModel(
            name="Manifesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "content",
                    models.TextField(help_text="Contenu intégral du manifeste (JSON ou Markdown)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current",
                    models.BooleanField(
                        default=True, help_text="Un seul manifeste actif à la fois"
                    ),
                ),
            ],
            options={
                "verbose_name": "Manifeste Global",
                "verbose_name_plural": "Manifestes",
            },
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Mots-clés ou catégories (séparés par des virgules)",
                max_length=255,
            ),
        ),
    ]
