# Generated by Django 5.2.2 on 2025-07-30 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0002_agentprofile_manifesto_alter_jaredlog_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(help_text="Message envoyé par l'utilisateur")),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Réponse générée par l'agent", null=True
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("private", "Privé (hors contexte professionnel)"),
                            ("personal", "Personnel (lié à une mission de l’agent)"),
                            ("shared", "Partagé (visible par tous les agents et Jared)"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Mots-clés pour retrouver ce message", max_length=255
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, help_text="Ce message est-il archivé ?"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ai_assistants.agentprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message entre utilisateur et agent",
                "verbose_name_plural": "Journal des Conversations IA",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AgentImpactReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("none", "Aucun"),
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Fort"),
                            ("critical", "Bloquant"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Note de synthèse générée automatiquement par l’agent"
                    ),
                ),
                (
                    "alert_jared",
                    models.BooleanField(
                        default=False, help_text="Doit-on notifier Jared d'une alerte critique ?"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai_assistants.agentprofile"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistants.agentmessagelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport d'Impact Automatique",
                "verbose_name_plural": "Rapports d'Impact IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
