# Generated by Django 5.2.2 on 2025-07-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0003_agentmessagelog_agentimpactreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentprofile",
            name="metadata",
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="activation_mode",
            field=models.JSONField(
                blank=True, default=dict, help_text="Modes et déclencheurs d’activation"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="communication_style",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Style de communication (ton, longueur, niveau de langue...)",
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="context_enrichment",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sources de données contextuelles, tonalité, enrichissement",
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="dependency_matrix",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Autres agents ou données nécessaires au bon fonctionnement",
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="emotion_profile",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tempérament de l’agent, empathie, réponses au stress",
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="ethical_constraints",
            field=models.JSONField(
                blank=True, default=dict, help_text="Comportements interdits, politiques sensibles"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="execution_metrics",
            field=models.JSONField(
                blank=True, default=dict, help_text="KPIs, objectifs, seuils de performance"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="integrations",
            field=models.JSONField(
                blank=True, default=dict, help_text="Stack technique, outils intégrés"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="learning_protocol",
            field=models.JSONField(
                blank=True, default=dict, help_text="Méthodologie d’apprentissage ou mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="security_protocol",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Protocoles de sécurité (chiffrement, anonymisation...)",
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="temperature",
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Outils disponibles (functions, file_search, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="usage_scope",
            field=models.JSONField(
                blank=True, default=dict, help_text="Responsabilités couvertes ou exclues"
            ),
        ),
    ]
