# Generated by Django 5.2.2 on 2025-07-31 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0004_remove_agentprofile_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmessagelog",
            name="agent_cible",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agentmessagelog",
            name="auteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auteur_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentmessagelog",
            name="confidentiel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentmessagelog",
            name="priorite",
            field=models.CharField(
                choices=[
                    ("low", "Basse"),
                    ("medium", "Moyenne"),
                    ("high", "Haute"),
                    ("critical", "Critique"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="agentmessagelog",
            name="reponse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentmessagelog",
            name="statut",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("alert", "Alerte"),
                    ("decision", "Décision"),
                    ("todo", "Tâche"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agentmessagelog",
            name="suivi",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agentimpactreport",
            name="alert_jared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agentimpactreport",
            name="summary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="activation_mode",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="communication_style",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="context_enrichment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="dependency_matrix",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="emotion_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="ethical_constraints",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="execution_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="integrations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="learning_protocol",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="security_protocol",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="tools",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="usage_scope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="agent_cible",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="confidentiel",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="reponse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="suivi",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
