# Generated by Django 5.2.2 on 2025-07-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0005_agentmessagelog_agent_cible_agentmessagelog_auteur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSystemContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("context_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_context",
                        to="ai_assistants.agentprofile",
                    ),
                ),
            ],
        ),
    ]
