# Generated by Django 5.2.5 on 2025-10-05 05:40

import uuid
from decimal import Decimal

import ai_assistants.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0008_add_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID corrélatif côté API/appelant.",
                        max_length=64,
                    ),
                ),
                (
                    "provider",
                    models.CharField(help_text="openai|anthropic|ollama|…", max_length=64),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="gpt-4o-mini|claude-3.7-haiku|llama3:8b|…", max_length=128
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tokens_in",
                    models.PositiveIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "tokens_out",
                    models.PositiveIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "cost_eur",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=10),
                ),
                ("input_excerpt", models.TextField(blank=True, default="")),
                ("output_excerpt", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Succès"),
                            ("error", "Erreur"),
                            ("blocked", "Bloqué (policy/budget)"),
                            ("rate_limited", "Rate limited"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Exécution d'agent",
                "verbose_name_plural": "Exécutions d'agents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("success", models.BooleanField(default=True)),
                ("args", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Appel d'outil",
                "verbose_name_plural": "Appels d'outils",
            },
        ),
        migrations.CreateModel(
            name="DailyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(default=ai_assistants.models.local_today)),
                (
                    "spent_eur",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=10),
                ),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Budget quotidien agent",
                "verbose_name_plural": "Budgets quotidiens agents",
            },
        ),
        migrations.CreateModel(
            name="UserSecurityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("secret_hue", models.PositiveSmallIntegerField(default=202)),
                ("hue_tolerance", models.PositiveSmallIntegerField(default=8)),
                ("emoji_order_hash", models.CharField(blank=True, default="", max_length=128)),
                ("emoji_nonce", models.CharField(blank=True, default="", max_length=32)),
                ("fail_count", models.PositiveIntegerField(default=0)),
                ("last_fail_at", models.DateTimeField(blank=True, null=True)),
                ("sandbox_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="agentimpactreport",
            options={
                "verbose_name": "Rapport d’impact agent",
                "verbose_name_plural": "Rapports d’impact agents",
            },
        ),
        migrations.AlterModelOptions(
            name="agentmessagelog",
            options={
                "verbose_name": "Log message agent",
                "verbose_name_plural": "Logs messages agents",
            },
        ),
        migrations.AlterModelOptions(
            name="agentprofile",
            options={
                "ordering": ["slug"],
                "verbose_name": "Profil d'agent",
                "verbose_name_plural": "Profils d'agents",
            },
        ),
        migrations.AlterModelOptions(
            name="agentsystemcontext",
            options={
                "verbose_name": "Contexte système d’agent",
                "verbose_name_plural": "Contextes système d’agent",
            },
        ),
        migrations.AlterModelOptions(
            name="jaredlog",
            options={
                "verbose_name": "Journal stratégique (Jared)",
                "verbose_name_plural": "Journaux stratégiques (Jared)",
            },
        ),
        migrations.AlterModelOptions(
            name="manifesto",
            options={
                "verbose_name": "Manifeste global",
                "verbose_name_plural": "Manifestes globaux",
            },
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="agent_cible",
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="auteur",
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="confidentiel",
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="priorite",
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="reponse",
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="statut",
        ),
        migrations.RemoveField(
            model_name="agentmessagelog",
            name="suivi",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="activation_mode",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="assistant_id",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="context_enrichment",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="dependency_matrix",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="emotion_profile",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="ethical_constraints",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="execution_metrics",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="integrations",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="learning_protocol",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="security_protocol",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="tools",
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="usage_scope",
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="alias",
            field=models.CharField(
                blank=True, default="", help_text="Alias/verbe métier.", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="manifest_hash_sha256",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="manifest_json",
            field=models.JSONField(
                default=dict, help_text="Manifeste complet v2.1 validé (source de vérité)."
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="profile_version",
            field=models.CharField(default="2.1.0", help_text="Semver du profil.", max_length=16),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="schema_version",
            field=models.CharField(default="2.1.0", editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="agentimpactreport",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_assistants.agentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="agentimpactreport",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="agentimpactreport",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_assistants.agentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="scope",
            field=models.CharField(
                choices=[("private", "Privé"), ("personal", "Personnel"), ("shared", "Partagé")],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agentmessagelog",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="communication_style",
            field=models.CharField(blank=True, default="Standard", max_length=255),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Résumé fonctionnel."),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="model",
            field=models.CharField(
                default="gpt-4o", help_text="Cache dérivé du manifeste.", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="name",
            field=models.CharField(help_text="Nom d'affichage de l'agent.", max_length=120),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="slug",
            field=models.SlugField(
                help_text="Identifiant court (ex: 'jared', 'claire'). Immuable après création.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="temperature",
            field=models.FloatField(default=0.4, help_text="Cache dérivé du manifeste."),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="agent_cible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_assistants.agentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="priorite",
            field=models.CharField(
                choices=[
                    ("low", "Faible"),
                    ("medium", "Moyenne"),
                    ("high", "Élevée"),
                    ("critical", "Critique"),
                ],
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="reponse",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="statut",
            field=models.CharField(
                choices=[
                    ("todo", "À faire"),
                    ("done", "Terminé"),
                    ("waiting", "En attente"),
                    ("alert", "Alerte"),
                    ("note", "Note"),
                    ("info", "Info"),
                ],
                default="todo",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="suivi",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jaredlog",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="manifesto",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="manifesto",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="manifesto",
            name="version",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name="agentimpactreport",
            index=models.Index(fields=["created_at"], name="ai_assistan_created_1664a0_idx"),
        ),
        migrations.AddIndex(
            model_name="agentimpactreport",
            index=models.Index(fields=["impact_level"], name="ai_assistan_impact__724cdd_idx"),
        ),
        migrations.AddIndex(
            model_name="agentmessagelog",
            index=models.Index(fields=["timestamp"], name="ai_assistan_timesta_f83a45_idx"),
        ),
        migrations.AddIndex(
            model_name="agentmessagelog",
            index=models.Index(fields=["agent", "scope"], name="ai_assistan_agent_i_67b2a9_idx"),
        ),
        migrations.AddIndex(
            model_name="jaredlog",
            index=models.Index(fields=["statut"], name="ai_assistan_statut_c345a7_idx"),
        ),
        migrations.AddIndex(
            model_name="jaredlog",
            index=models.Index(fields=["priorite"], name="ai_assistan_priorit_fc5479_idx"),
        ),
        migrations.AddIndex(
            model_name="jaredlog",
            index=models.Index(fields=["horodatage"], name="ai_assistan_horodat_11d2f8_idx"),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="ai_assistants.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="agenttoolcall",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_calls",
                to="ai_assistants.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="dailybudget",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_budgets",
                to="ai_assistants.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="usersecurityprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["agent", "created_at"], name="ai_assistan_agent_i_6cd353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["provider", "model"], name="ai_assistan_provide_e25bd8_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["status"], name="ai_assistan_status_9c5852_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttoolcall",
            index=models.Index(fields=["name", "created_at"], name="ai_assistan_name_838c9e_idx"),
        ),
        migrations.AddIndex(
            model_name="dailybudget",
            index=models.Index(fields=["agent", "date"], name="ai_assistan_agent_i_0f7359_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailybudget",
            unique_together={("agent", "date")},
        ),
    ]
