# Generated by Django 5.2.5 on 2025-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistants", "0010_dojo_conversations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="ai_assistan_creator_c0e043_idx",
            old_name="dojo_conv_creator_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="ai_assistan_agent_i_d051bc_idx",
            old_name="dojo_conv_agent_status_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationauditlog",
            new_name="ai_assistan_action_816995_idx",
            old_name="dojo_audit_action_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationauditlog",
            new_name="ai_assistan_object__fa4993_idx",
            old_name="dojo_audit_object_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="ai_assistan_convers_dc5b3e_idx",
            old_name="dojo_msg_conv_created_idx",
        ),
        migrations.AddField(
            model_name="conversationauditlog",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
