# Generated by Django 5.2.5 on 2025-10-17 09:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EotpChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                            ("locked", "Locked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("code_hash", models.TextField()),
                ("algo", models.CharField(default="argon2id", max_length=16)),
                ("pepper_id", models.CharField(max_length=32)),
                ("tries_count", models.PositiveIntegerField(default=0)),
                ("resend_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("context_ua", models.CharField(blank=True, max_length=56, null=True)),
                ("context_ip_prefix", models.CharField(blank=True, max_length=64, null=True)),
                ("corr_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eotp_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "eotp_challenge",
                "indexes": [
                    models.Index(fields=["session_key"], name="idx_eotp_session_key"),
                    models.Index(fields=["status", "expires_at"], name="idx_eotp_status_expires"),
                    models.Index(fields=["user", "created_at"], name="idx_eotp_user_created"),
                    models.Index(fields=["created_at"], name="idx_eotp_created"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="eotp_expires_after_created",
                    )
                ],
            },
        ),
    ]
