# Generated by Django 5.2.5 on 2025-10-18 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eotp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EotpPassphrase",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="eotp_passphrase",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("hash", models.TextField()),
                ("algo", models.CharField(default="argon2id", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "eotp_passphrase",
                "indexes": [models.Index(fields=["updated_at"], name="idx_eotpp_updated")],
            },
        ),
    ]
